<!DOCTYPE html>
<html lang='en'>

<head>
  <?php include 'layout/header.phtml' ?>
</head>

<body>

  <div class="grid-layout">
    <header>
      <?php include 'layout/navigation.phtml' ?>
    </header>
    <main>
      <?php include $page ?>
    </main>
    <footer>
      <?php include 'layout/footer.phtml' ?>
    </footer>
  </div>

  <!-- <script src="/js/site/home.js"></script> -->
  <script src="/js/<?= $scMetaPath; ?>.js">
  </script>
</body>

</html>