<nav class="navbar">
  <div class="brand-title">
    <!-- <img class="logo-avatar" src="/img/site/quickstart.png" alt="QuickStart"> -->
    <span>QuickStart</span>
  </div>

  <a href="#" class="toggle-button">
    <span class="bar"></span>
    <span class="bar"></span>
    <span class="bar"></span>
  </a>
  <div class="navbar-links">
    <ul class="links">
      <li>
        <a <?= $scMetaController === 'Home' ? 'class="active"' : '' ?> href=" /<?= $scMetaLanguage ?>/Home">
          <?= $trans['menu']['home'] ?>
        </a>
      </li>
      <li>
        <a <?= $scMetaController === 'About' ? 'class="active"' : '' ?> href=" /<?= $scMetaLanguage ?>/About">
          <?= $trans['menu']['about'] ?>
        </a>
      </li>
      <li>
        <a <?= $scMetaController === 'Services' ? 'class="active"' : '' ?> href=" /<?= $scMetaLanguage ?>/Services">
          <?= $trans['menu']['services'] ?>
        </a>
      </li>
      <li>
        <a <?= $scMetaController === 'Products' ? 'class="active"' : '' ?> href=" /<?= $scMetaLanguage ?>/Products">
          <?= $trans['menu']['products'] ?>
        </a>
      </li>
      <li>
        <a <?= $scMetaController === 'Sales' ? 'class="active"' : '' ?> href=" /<?= $scMetaLanguage ?>/Sales">
          <?= $trans['menu']['sales'] ?>
        </a>
      </li>
      <li>
        <a <?= $scMetaController === 'Contact' ? 'class="active"' : '' ?> href=" /<?= $scMetaLanguage ?>/Contact">
          <?= $trans['menu']['contact'] ?>
        </a>
      </li>
    </ul>
    <ul class="links-lang">
      <li><a href="/en/<?= $scMetaController ?>">En</a></li>
      <li><a href="/nl/<?= $scMetaController ?>">Nl</a></li>
      <li><a href="/fr/<?= $scMetaController ?>">Fr</a></li>
    </ul>
  </div>
</nav>